### ISSUE TITLE
Two different speakers for one line (poetry/drama)

### ISSUE THREAD

**Issue by ClaDan** [SASDigitalHumanitiesTraining/TextEncoding#16]
I am trying to encode a Roman play which is written in verse. How may I indicate that a character's cue begins within the same metrical line as the end of a previous cue? When I add another "speech" or "speaker" element, my "l" tag appears to be ill-formed. 

![TEI sample Miles gloriosus](https://user-images.githubusercontent.com/84458640/118828519-a1558c00-b8bd-11eb-8b2c-b4ec8e20434d.png)

Thank you very much!

**Comment by gabrielbodard** [comment]
Ah, this is a slightly complex one. Your XML is indeed ill-formed, since you have an `<l>` starting inside a `<sp>` but the speech ending before the line does. The best solution to this is probably to break the verse line into two `<l>` tags, with attributes to make clear that it is a single line, e.g.:

~~~~
<l part-"I">sed ubi Artotrogus hic est?</l></sp>
<sp><l part="F">Artotrogus Stat propter virum</l>
~~~~

Where `part="I"` and `part="F"` mean "this tag is the **initial** part of a single line" and "this tag is the **final** part of a single line," respectively.

If you number the lines, you could repeat the `@n` on these two half-lines, to make it even clearer to the reader what is going on.
