### ISSUE TITLE
Coding for a speech that is not in a drama

### ISSUE THREAD

**Issue by s0crates2** [SASDigitalHumanitiesTraining/TextEncoding#24]
This may be a question about indexing and not coding, because I don't understand the difference.  We saw an example of TEI coding for plays,  which note a speech and speaker `(sp>` and `<speaker>`, but how does one tag a speech in a different kind of text?  

My exercise is from the first part of the Illiad, which includes the speech "Sons of Atreus",  but Oxygen doesn't like either of those.  If I wanted  to collect all parts of the text which are in first person, how would that be coded? I don't think `<q>` serves here. Or would indexing fix that? 

` <lg>
               <l>and he besought the Achaeans, but most of all the two sons of <name>Atreus</name>, who</l>
               <l>were their chiefs. "Sons of Atreus", he cried "and all other Achaeans, may the</l>
               <l>gods who dwell in <placeName>Olympus</placeName> grant you to sack the city of 
 <placeName>Priam</placeName>, and to reach</l>
               <l>your homes in safety;</l>
            </lg>
            <lg>
               <l>but free my daughter, and accept a ransom for her, in reverence to <name>Apollo</name>,</l>
               <l>son of <name>Zeus</name>." On this the rest of the Achaeans with one voice were for</l>
               <l>respecting the priest and taking the ransom that he offered; but not so</l>
               <l><name>Agamemnon</name></l>
            </lg>`

Thanks, 
Greta

**Comment by gabrielbodard** [comment]
Actually I think `<q>` may be the best element for this, since we're talking about direct speech, no? But you would have to either close the speech at the end of each verse-line and re-open it, so as to avoid overlapping with the `<l>` tags, or use some other mechanism (anchors or stand-off markup) to indicate the start and end of each speech.

Does Perseus mark direct speech at all in their XML of the Iliad?

**Comment by gabrielbodard** [comment]
Answering my own question ([Perseus's Iliad in XML](http://www.perseus.tufts.edu/hopper/xmlchunk?doc=Perseus%3Atext%3A1999.01.0134%3Abook%3D1%3Acard%3D1)) … they do tag speech in the English translation, incorrectly using `<quote>`, and they don't tag verse lines (perhaps because it is a prose translation?).

**Comment by s0crates2** [comment]
Thank you!
