### ISSUE TITLE
https://epidoc.stoa.org/schema/latest/tei-epidoc.rng

### ISSUE THREAD

**Issue by NicolePohl** [SASDigitalHumanitiesTraining/TextEncoding#9]
I started watching the How to Use Oxygen video and am struggling to get the following file into a folder:

https://epidoc.stoa.org/schema/latest/tei-epidoc.rng

**Comment by strill66** [comment]
I had a similar problem - the 'rng' file seems to be composed of plain text, is that right? I also had an issue with downloading the schema (and eventually downloaded version 9.2 from Epidoc). I'm not sure if part of the problem is that I'd put this straight into oxygen (it was only latterly that I realised I was supposed to create a file on my desktop). I have now done both, and the oxygen file seems to be working, although when I tried to take out the URL in the TEI header, it wouldn't validate. Hopefully, the files below give you a sense of just how much I've got wrong ....
![Epidoc 2021 - Trial 1](https://user-images.githubusercontent.com/84331025/118507379-14c49580-b726-11eb-940b-a60e746f78a0.png)
![Desktop shortcut](https://user-images.githubusercontent.com/84331025/118507420-1ee69400-b726-11eb-8317-3ffe278f09f4.png)
![Epidoc 2021 - Trial - with URL](https://user-images.githubusercontent.com/84331025/118507430-20b05780-b726-11eb-9a3a-f49b5a60d792.png)
![Epidoc 2021 - Trial -without URL](https://user-images.githubusercontent.com/84331025/118507431-2148ee00-b726-11eb-8ad4-d0bc03c868f3.png)

**Comment by gabrielbodard** [comment]
Hi both,

Ignore this part for now. That is the EpiDoc schema (which you won't need unless you choose that strand for the second half of the workshop). We were reusing the intro to Oxygen video from another workshop, and I should have mentioned to skip that part. From this video, just pay attention to the comments on how to use Oxygen, inserting element tags, keyboard shortcuts, etc.

Hope that helps?

**Comment by strill66** [comment]
Hi Gabriel,
yes, although I was planning on following the EpiDoc strand (and am also mindful that for the project Cordelia and I will be working on, we will be agreeing a schema with KDL, so presumably we'll need to know how to adapt Oxygen to be compatible with that at some point?).
Cheers, S

**Comment by gabrielbodard** [comment]
Hi @strill66 : from what I can see from your screenshots, you have saved the schema as a file named `Epidoc-schema.rng` but then in your XML file you are pointing to a local schema names `tei-epidoc.rng`, which is why the schema is not recognised. If you change the local name of the schema on your desktop to "tei-epidoc", it should now work?

Having said that, if you leave the full URL of the schema at epidoc.stoa.org, it should also still work. Each "validate" command will just take a second or so longer that if it were local.

Does this help?

**Comment by strill66** [comment]
@gabrielbodard 

OK, I did that. It works while I keep in the URL but if I take it out, I get the error message 'missing children', and when I click in the rng file in Oxygen the below is what I see (also with a 'missing children' error code). Sorry about this - I've used Oxygen before but not linked it to anything!
![View of rng file in Oxygen](https://user-images.githubusercontent.com/84331025/118518419-03808680-b730-11eb-9ad9-c9958816dd02.png)

**Comment by gabrielbodard** [comment]
I'm not sure what's happened to the schema above, but it looks like is either broken, or an empty schema template file, or something?

Try right-clicking on the schema link in the issue above (or [here](https://epidoc.stoa.org/schema/latest/tei-epidoc.rng)), and select "Save link as…" to get a new copy of the `tei-epidoc.rng` schema file. You don't need to open this file—just put it in the same folder as your XML file with the lines

~~~~
<?xml-model href="tei-epidoc.rng" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="tei-epidoc.rng" schematypens="http://purl.oclc.org/dsdl/schematron"?>
~~~~

at the top, and it should validate your files for you. For the purposes of this exercise, it shouldn't make much difference from using TEI All, anyway.

**Comment by strill66** [comment]
@gabrielbodard - thank you - I did as you suggested above, and deleted the 'broken/empty schema' file. I then found that if - in Oxygen - I used 'Open URL' and pasted the link in, that the version of tei-epidoc.rng I could see would now validate and that I could save it as a file in my project (which I've simply called Epidoc 2021). I hope this means all will be fine for later in the week.

**Comment by strill66** [comment]
@gabrielbodard PS. the project is called 'Epidoc 2021', the file is there as 'tei-epidoc.rng'. Tomorrow, I will start working on my new document

**Comment by gabrielbodard** [comment]
@strill66 yes, I think that will also work. Glad you've got it validating!
